---
blueprint:
  name: ttpforge
  packer_templates:
    image_values:
      name: ubuntu
      version: jammy
    # Provisioning user
    user: ubuntu
    # AMI specific configurations
    ami:
      instance_type: c4.xlarge
      ssh_username: ubuntu
    # Tags for created odysseys
    tag:
      name: l50/ttpforge
      version: latest
    # Container specific configurations
    container:
      image_hashes:
        - arch: amd64
          os: linux
        - arch: arm64
          os: linux
      registry:
        server: ghcr.io
        username: l50
      workdir: /home/ubuntu
