---
blueprint:
  name: ttpforge
  tag:
    name: l50/ttpforge
    version: latest

packer_templates:
  - image_values:
      name: ubuntu
      version: jammy
    user: ubuntu

# AMI specific configurations
ami:
  instance_type: t3.medium
  region: us-east-1

# Container specific configurations
container:
  workdir: /home/ubuntu
  registry:
    server: ghcr.io
    username: l50
