---
# Area
- name: area/blueprints
  color: "8fbcbc" # teal
  description: >-
    Changes made to blueprint configurations and scripts

- name: area/cmd
  color: "a18fbf" # purple
  description: >-
    Changes made to command line utilities

- name: area/docs
  color: "8fbc8f"
  description: >-
    Changes made to project documentation

- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to github actions

- name: area/magefiles
  color: "7BD7E0"
  description: >-
    Changes made to Magefiles

- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks

- name: area/templates
  color: "bc8f8f"
  description: >-
    Changes made to template files

- name: area/go-mod-sum
  color: "7BD7E0"
  description: >-
    Changes made to go.mod and go.sum

# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"

# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"

# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c"
