---
# Area
- name: area/dockerfiles
  color: "8fbcbc" # teal
  description: >-
    Changes made to Dockerfiles and Docker configurations

- name: area/packer
  color: "bc8f8f" # salmon
  description: >-
    Changes made to Packer templates and configurations

- name: area/docs
  color: "8fbc8f" # light green
  description: >-
    Changes made to project documentation

- name: area/github
  color: "72ccf3" # light blue
  description: >-
    Changes made to GitHub Actions workflows

- name: area/taskfile
  color: "7BD7E0" # cyan
  description: >-
    Changes made to Taskfile configurations

- name: area/pre-commit
  color: "BC9BE3" # lavender
  description: >-
    Changes made to pre-commit hooks

# Tool-specific labels
- name: tool/atomic-red-team
  color: "FF6B6B" # red
  description: >-
    Changes related to Atomic Red Team configurations

- name: tool/attack-box
  color: "4ECDC4" # turquoise
  description: >-
    Changes related to Attack Box configurations

- name: tool/runzero
  color: "45B7D1" # sky blue
  description: >-
    Changes related to RunZero Explorer configurations

- name: tool/sliver
  color: "96CEB4" # mint
  description: >-
    Changes related to Sliver C2 configurations

- name: tool/ttpforge
  color: "DDA0DD" # plum
  description: >-
    Changes related to TTPForge configurations

# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"

# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"

# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c"
