---
builds:
  - id: "warpgate"

    binary: wg

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    # GOARM to build for when GOARCH is arm.
    goarm:
      - "6"
      - "7"

    # GOAMD64 to build when GOARCH is amd64.
    goamd64:
      - v2
      - v3
