---
project_name: wg

release:
  github:
    owner: CowDogMoo
    name: warpgate

builds:
  - id: "warpgate"
    binary: wg
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3
    env:
      - CGO_ENABLED=0
    tags:
      - containers_image_openpgp
    goarm:
      - "6"
      - "7"
