---
version: 2

# Snapshot configuration for non-release builds
# Use git describe format for version strings
snapshot:
  version_template: "{{ .Version }}-next"

builds:
  - id: "warpgate"

    binary: warpgate

    main: ./cmd/warpgate

    # Inject version info via ldflags
    # Use {{.Summary}} to get git describe format (e.g., v3.0.0-1-gc1b0525)
    ldflags:
      - -s -w
      - -X main.version={{.Summary}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

    goos:
      - linux
      - darwin
      # - windows

    goarch:
      - amd64
      - arm
      - arm64

    # GOARM to build for when GOARCH is arm.
    goarm:
      - 6
      - 7

    # GOAMD64 to build when GOARCH is amd64.
    goamd64:
      - v2
      - v3

    hooks:
      pre: go mod tidy
