---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  docker:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/docker/Taskfile.yaml"
  github:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/github/Taskfile.yaml"
  packer:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/packer/Taskfile.yaml"
  pre-commit:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/pre-commit/Taskfile.yaml"
  secrets:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/secrets/Taskfile.yaml"
  terraform:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/terraform/Taskfile.yaml"
  renovate:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/renovate/Taskfile.yaml"

tasks:
  default:
    desc: "Run all CI tasks"
    cmds:
      - task: run-pre-commit

  run-pre-commit:
    desc: "Update, clear cache, and run pre-commit hooks"
    cmds:
      - task: pre-commit:update-hooks
      - task: pre-commit:clear-cache
      - task: pre-commit:run-hooks

  run-image-builder-action:
    desc: "Run GitHub Actions image-builder workflow using act. Optionally specify TEMPLATE"
    vars:
      TEMPLATE: '{{.TEMPLATE | default ""}}'
    cmds:
      - ./scripts/taskfile/run-image-builder.sh {{.TEMPLATE}}

  discover-templates:
    desc: "Discover templates from all configured sources"
    cmds:
      - |
        echo "Discovering templates from configured sources..."
        python3 scripts/taskfile/discover-templates.py \
          --config warpgate-config.yaml \
          --output discovered-templates.json \
          --format json \
          --verbose

  discover-templates-matrix:
    desc: "Generate GitHub Actions matrix from discovered templates"
    cmds:
      - |
        echo "Generating GitHub Actions matrix..."
        python3 scripts/taskfile/discover-templates.py \
          --config warpgate-config.yaml \
          --output .github/workflows/template-matrix.json \
          --format github-matrix \
          --verbose

  template-build:
    desc: Build a template image from anywhere in the repo
    env:
      PACKER_PATH: '{{.PACKER_CMD | default "packer"}}'
    vars:
      RESOLVED_TEMPLATE_DIR:
        sh: |
          python3 scripts/taskfile/resolve-template-dir.py \
            {{if .TEMPLATE_NAME}}--template-name "{{.TEMPLATE_NAME}}"{{end}} \
            {{if .TEMPLATE_DIR}}--template-dir "{{.TEMPLATE_DIR}}"{{end}}
    cmds:
      - task: packer:cleanup-packer-manifest
        vars:
          MANIFEST_PATH: '{{.MANIFEST_PATH | default "./manifest.json"}}'

      - task: packer:packer-template-build
        vars:
          COMMAND: "build"
          TEMPLATE_NAME: "{{.TEMPLATE_NAME}}"
          TEMPLATE_DIR: "{{.RESOLVED_TEMPLATE_DIR}}"
          ONLY: '{{.ONLY   | default ""}}'
          VARS: '{{.VARS   | default ""}}'
          FORCE: '{{.FORCE | default "false"}}'

  template-init:
    desc: "Initialize a Packer template from anywhere in the repo (supports multi-source)"
    env:
      PACKER_PATH: '{{.PACKER_CMD | default "packer"}}'
    vars:
      RESOLVED_TEMPLATE_DIR:
        sh: |
          python3 scripts/taskfile/resolve-template-dir.py \
            {{if .TEMPLATE_NAME}}--template-name "{{.TEMPLATE_NAME}}"{{end}} \
            {{if .TEMPLATE_DIR}}--template-dir "{{.TEMPLATE_DIR}}"{{end}}
    cmds:
      - task: packer:packer-init
        vars:
          TEMPLATE_NAME: "{{.TEMPLATE_NAME}}"
          TEMPLATE_DIR: "{{.RESOLVED_TEMPLATE_DIR}}"
          VARS: '{{.VARS | default ""}}'

  template-validate:
    desc: "Validate a template packer template from anywhere in the repo"
    cmds:
      - task: packer:_packer-base
        vars:
          COMMAND: "validate"
          TEMPLATE_NAME: "{{.TEMPLATE_NAME}}"
          VAR_FILE: '{{.VAR_FILE | default ""}}'

  template-push:
    desc: "Push multi-architecture Docker images using Packer manifest"
    requires:
      vars: ["NAMESPACE", "IMAGE_NAME", "GITHUB_TOKEN", "GITHUB_USER"]
    vars:
      REGISTRY: '{{ .REGISTRY | default "ghcr.io" }}'
      NAMESPACE: "{{ .NAMESPACE }}"
      IMAGE_NAME: "{{ .IMAGE_NAME }}"
      TAG: '{{ .TAG | default "latest" }}'
      GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
      GITHUB_USER: "{{ .GITHUB_USER }}"
      MANIFEST_PATH: '{{ .MANIFEST_PATH | default "./manifest.json" }}'
      ARM64_HASH:
        sh: |
          if [ -f "{{ .MANIFEST_PATH }}" ]; then
            jq -r '.builds[] | select(.name == "arm64") | .artifact_id' {{ .MANIFEST_PATH }}
          else
            echo "Error: Manifest file not found at {{ .MANIFEST_PATH }}" >&2
            exit 1
          fi
      AMD64_HASH:
        sh: |
          if [ -f "{{ .MANIFEST_PATH }}" ]; then
            jq -r '.builds[] | select(.name == "amd64") | .artifact_id' {{ .MANIFEST_PATH }}
          else
            echo "Error: Manifest file not found at {{ .MANIFEST_PATH }}" >&2
            exit 1
          fi
    cmds:
      - ./scripts/taskfile/prepare-template-push.sh {{ .MANIFEST_PATH }}
      - task: docker:push-multi-arch
        vars:
          REGISTRY: "{{ .REGISTRY }}"
          NAMESPACE: "{{ .NAMESPACE }}"
          IMAGE_NAME: "{{ .IMAGE_NAME }}"
          TAG: "{{ .TAG }}"
          ARM64_HASH: "{{ .ARM64_HASH }}"
          AMD64_HASH: "{{ .AMD64_HASH }}"
          GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
          GITHUB_USER: "{{ .GITHUB_USER }}"

  template-push-digest:
    desc: "Push architecture-specific Docker image by digest"
    requires:
      vars: ["NAMESPACE", "IMAGE_NAME", "ARCH", "GITHUB_TOKEN", "GITHUB_USER"]
    vars:
      REGISTRY: '{{ .REGISTRY | default "ghcr.io" }}'
      NAMESPACE: "{{ .NAMESPACE }}"
      IMAGE_NAME: "{{ .IMAGE_NAME }}"
      ARCH: "{{ .ARCH }}"
      GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
      GITHUB_USER: "{{ .GITHUB_USER }}"
      MANIFEST_PATH: '{{ .MANIFEST_PATH | default "./manifest.json" }}'
    cmds:
      - ./scripts/taskfile/push-digest.sh "{{ .REGISTRY }}" "{{ .NAMESPACE }}" "{{ .IMAGE_NAME }}" "{{ .ARCH }}" "{{ .MANIFEST_PATH }}" "{{ .GITHUB_USER }}" "{{ .GITHUB_TOKEN }}"

  template-create-manifest:
    desc: "Create and push multi-architecture manifest"
    requires:
      vars: ["NAMESPACE", "IMAGE_NAME", "GITHUB_TOKEN", "GITHUB_USER"]
    vars:
      REGISTRY: '{{ .REGISTRY | default "ghcr.io" }}'
      NAMESPACE: "{{ .NAMESPACE }}"
      IMAGE_NAME: "{{ .IMAGE_NAME }}"
      TAG: '{{ .TAG | default "latest" }}'
      GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
      GITHUB_USER: "{{ .GITHUB_USER }}"
    cmds:
      - ./scripts/taskfile/create-manifest.sh "{{ .REGISTRY }}" "{{ .NAMESPACE }}" "{{ .IMAGE_NAME }}" "{{ .TAG }}" "{{ .GITHUB_USER }}" "{{ .GITHUB_TOKEN }}"
