---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BINARY_NAME: warpgate
  CMD_PATH: ./cmd/warpgate

includes:
  go:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/go/Taskfile.yaml"
    vars:
      BINARY_NAME: warpgate
      CMD_PATH: ./cmd/warpgate
  docker:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/docker/Taskfile.yaml"
  github:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/github/Taskfile.yaml"
  pre-commit:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/pre-commit/Taskfile.yaml"
  secrets:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/secrets/Taskfile.yaml"
  renovate:
    taskfile: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/renovate/Taskfile.yaml"

tasks:
  default:
    desc: Build, test, and clean
    cmds:
      - task: go:default

  schema:generate:
    desc: Generate JSON schema for warpgate templates
    cmds:
      - go run ./cmd/schema-gen -o schema/warpgate-template.json
    sources:
      - pkg/builder/config.go
      - cmd/schema-gen/main.go
    generates:
      - schema/warpgate-template.json

  schema:validate:
    desc: Validate that JSON schema is up to date
    cmds:
      - task: schema:generate
      - git diff --exit-code schema/warpgate-template.json || (echo "Schema is out of date. Run 'task schema:generate' and commit the changes." && exit 1)
