---
blueprint:
  name: windows
  packer_templates:
    image_values:
      name: Windows_Server
      version: 2019
    # Provisioning user
    user: Administrator
    # AMI specific configurations
    ami:
      instance_type: t3.micro
      ssh_username: Administrator
    # Tags for created odysseys
    tag:
      name: windows-server
      version: 2019
