---
blueprint:
  name: attack-box

packer_templates:
  - name: ansible-attack-box.pkr.hcl
    base:
      name: cisagov/docker-kali-ansible
      version: latest
    systemd: true
    tag:
      name: cowdogmoo/attack-box
      version: latest

container:
  workdir: /home/kali
  entrypoint: "/run/docker-entrypoint.sh ; zsh"
  user: kali
  registry:
    server: ghcr.io
    username: cowdogmoo
