---
blueprint:
  name: attack-box
  packer_templates:
    image_values:
      name: kalilinux/kali-rolling
      version: latest
    # Provisioning user
    user: kali
    # Tags for created odysseys
    ami:
      instance_type: t3.micro
      ssh_username: kali
    # Tags for created odysseys
    tag:
      name: l50/attack-box
      version: latest
    container:
      image_hashes:
        - arch: amd64
          os: linux
        - arch: arm64
          os: linux
      registry:
        server: ghcr.io
        username: l50
      workdir: /home/kali
