---
blueprint:
  name: attack-box
  packer_templates:
    image_values:
      name: kalilinux/kali-rolling
      version: latest
    # Provisioning user
    user: kali
    # AMI specific configurations
    ami:
      instance_type: t3.micro
      region: us-east-1
      ssh_username: kali
    # Tags for created odysseys
    tag:
      name: cowdogmoo/attack-box
      version: latest
    # Container specific configurations
    container:
      image_hashes:
        - arch: amd64
          os: linux
      registry:
        server: ghcr.io
        username: cowdogmoo
      workdir: /home/kali
      entrypoint: "/run/docker-entrypoint.sh ; zsh"
