---
blueprint:
  name: attack-box
  packer_templates:
    image_values:
      name: kalilinux/kali-rolling
      version: latest
    # Provisioning user
    user: kali
    # AMI specific configurations
    ami:
      instance_type: t3.large
      ssh_username: kali
    # Tags for created odysseys
    tag:
      name: cowdogmoo/attack-box
      version: latest
