---
# Set the debug level, which affects
# the output verbosity.
# Required to be present in any config.yaml.
debug: false

# Set the log level, which affects
# the output verbosity.
# Required to be present in any config.yaml.
log:
  format: text
  level: info

blueprint:
  name: ansible-vnc-zsh
  path: blueprints/ansible-vnc-zsh

packer_templates:
  - name: ubuntu-vnc.pkr.hcl
    base:
      name: ubuntu
      version: latest
    systemd: false
    tag:
      name: cowdogmoo/ansible-vnc
      version: latest

  - name: ubuntu-systemd-vnc.pkr.hcl
    base:
      name: geerlingguy/docker-ubuntu2204-ansible
      version: latest
    systemd: true
    tag:
      name: cowdogmoo/ansible-systemd-vnc
      version: latest
