---
debug: false

blueprint:
  name: ansible-vnc-zsh
  path: blueprints/ansible-vnc-zsh

packer_templates:
  - name: ubuntu-vnc.pkr.hcl
    base:
      name: ubuntu
      version: latest
    systemd: false
    tag:
      name: ghcr.io/cowdogmoo/ansible-vnc
      version: latest

  - name: ubuntu-systemd-vnc.pkr.hcl
    base:
      name: geerlingguy/docker-ubuntu2204-ansible
      version: latest
    systemd: true
    tag:
      name: ghcr.io/cowdogmoo/ansible-systemd-vnc
      version: latest
