---
blueprint:
  name: ansible-vnc-zsh

packer_templates:
  - name: ubuntu-vnc-zsh.pkr.hcl
    base:
      name: ubuntu
      version: latest
    systemd: false
    tag:
      name: cowdogmoo/ansible-vnc-zsh
      version: latest

  - name: ubuntu-systemd-vnc-zsh.pkr.hcl
    base:
      name: geerlingguy/docker-ubuntu2204-ansible
      version: latest
    systemd: true
    tag:
      name: cowdogmoo/ansible-systemd-vnc-zsh
      version: latest
