---
blueprint:
  name: atomic-red-team

packer_templates:
  - name: atomic-red-team.pkr.hcl
    base:
      name: ubuntu
      version: jammy
    tag:
      name: l50/atomic-red-team
      version: latest
    user: root

# AMI specific configurations
ami:
  instance_type: t3.medium
  region: us-east-1
  ssh_username: ubuntu

container:
  workdir: /root/AtomicRedTeam
  registry:
    server: ghcr.io
    username: l50
