---
blueprint:
  name: atomic-red-team

packer_templates:
  - name: atomic-red-team.pkr.hcl
    base:
      name: ubuntu
      version: jammy
    tag:
      name: l50/atomic-red-team
      version: latest

container:
  workdir: /root/AtomicRedTeam
  user: root
  registry:
    server: ghcr.io
    username: l50
