---
blueprint:
  name: atomic-red-team
  tag:
    name: l50/atomic-red-team
    version: latest

packer_templates:
  - image_values:
      name: ubuntu
      version: jammy
    user: root

# AMI specific configurations
ami:
  instance_type: t3.medium
  region: us-east-1
  ssh_username: ubuntu

container:
  workdir: /root/AtomicRedTeam
  registry:
    server: ghcr.io
    username: l50
