---
blueprint:
  name: runzero-explorer
  tag:
    name: cowdogmoo/runzero-explorer
    version: latest

packer_templates:
  - image_values:
      name: ubuntu
      version: jammy
    user: ubuntu

container:
  workdir: /home/ubuntu
  image_hashes:
    - arch: amd64
      os: linux
    - arch: arm64
      os: linux
  registry:
    server: ghcr.io
    username: cowdogmoo
