---
blueprint:
  name: runzero-explorer

packer_templates:
  - name: runzero-explorer.pkr.hcl
    base:
      name: ubuntu
      version: noble
    tag:
      name: cowdogmoo/runzero-explorer
      version: latest

container:
  workdir: /home/ubuntu
  # entrypoint: "/run/docker-entrypoint.sh ; sh"
  user: ubuntu
  registry:
    server: ghcr.io
    username: cowdogmoo
