---
blueprint:
  name: runzero-explorer

packer_templates:
  - name: runzero-explorer.pkr.hcl
    base:
      name: ubuntu
      version: jammy
    tag:
      name: cowdogmoo/runzero-explorer
      version: latest
    user: ubuntu

container:
  workdir: /home/ubuntu
  registry:
    server: ghcr.io
    username: cowdogmoo
