---
blueprint:
  name: sliver
  tag:
    name: l50/sliver
    version: latest

packer_templates:
  - image_values:
      name: ubuntu
      version: jammy
    user: sliver

# AMI specific configurations
ami:
  instance_type: t3.medium
  region: us-east-1

container:
  workdir: /home/sliver
  registry:
    server: ghcr.io
    username: l50
