---
blueprint:
  name: sliver

packer_templates:
  - name: sliver.pkr.hcl
    base:
      name: ubuntu
      version: jammy
    tag:
      name: l50/sliver
      version: latest
    user: sliver

# AMI specific configurations
ami:
  instance_type: t3.medium
  region: us-east-1

container:
  workdir: /home/sliver
  # entrypoint: "/run/docker-entrypoint.sh ; sh"
  registry:
    server: ghcr.io
    username: l50
