---
blueprint:
  name: sliver
  packer_templates:
    image_values:
      name: ubuntu
      version: jammy
    # Provisioning user
    user: sliver
    # AMI specific configurations
    ami:
      instance_type: c4.xlarge
      region: us-east-1
      ssh_username: ubuntu
    # Tags for created odysseys
    tag:
      name: l50/sliver
      version: latest
    # Container specific configurations
    container:
      image_hashes:
        - arch: amd64
          os: linux
        - arch: arm64
          os: linux
      registry:
        server: ghcr.io
        username: l50
      workdir: /home/sliver
