---
name: Container Image Builder
on:
  pull_request:
  push:
    branches: [main, container]

env:
  PRODUCT_VERSION: "latest"

jobs:
  container-image-builder:
    name: Build container images using warpgate
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.21.0"
          cache-dependency-path: "**/*.sum"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Install dependencies
        run: |
          go install github.com/goreleaser/goreleaser@latest
      - name: Set up warpgate
        run: |
          go mod tidy
          go build -o wg
          sudo mv wg /usr/local/bin/wg

      - name: Clone ansible-collection-workstation
        run: |
          mkdir -p ~/cowdogmoo
          git clone https://github.com/CowDogMoo/ansible-collection-workstation.git ~/cowdogmoo/ansible-collection-workstation

      - name: Run image builder for each blueprint
        run: |
          # Ensure this script runs from the repository root.
          cd ${{ github.workspace }}

          for blueprintRelPath in $(find blueprints -name config.yaml); do
              echo "Processing blueprint: $blueprintRelPath"

              # Construct the absolute path for the blueprint.
              blueprintPath="${PWD}/${blueprintRelPath}"
              echo "Blueprint absolute path: $blueprintPath"

              # Verify the provisioning path.
              provisioningPath="/home/runner/cowdogmoo/ansible-collection-workstation"
              echo "Provisioning path: $provisioningPath"

              # Run the wg imageBuilder command with the correct paths.
              wg imageBuilder -b "$blueprintPath" -p "$provisioningPath"
          done
