---
name: Container Image Builder
on:
  pull_request:
  push:
    branches: [main]

env:
  PRODUCT_VERSION: "latest"
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  generate-blueprints:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Generate list of blueprints
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find blueprints -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -c -s 'split("\n")[:-1]')"

  container-image-builder:
    needs: generate-blueprints
    name: Build container images using warpgate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blueprint: ${{fromJson(needs.generate-blueprints.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Pull images
        run: |
          docker pull --platform linux/amd64 geerlingguy/docker-ubuntu2204-ansible:latest
          docker pull --platform linux/arm64 geerlingguy/docker-ubuntu2204-ansible:latest

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.BOT_TOKEN }}"

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: "1.21.5"
          cache-dependency-path: "**/*.sum"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Set up warpgate
        run: |
          go mod tidy
          go build -o wg
          sudo mv wg /usr/local/bin/wg

      - name: Clone ansible-collection-workstation
        run: |
          mkdir -p $HOME/cowdogmoo
          git clone https://github.com/CowDogMoo/ansible-collection-workstation.git $HOME/cowdogmoo/ansible-collection-workstation

      - name: Make repository name lowercase
        id: lower-repo
        run: |
          echo "repo_owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "image_name_lowercase=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Run image builder for each blueprint
        run: |
          # Run the wg imageBuilder command with the correct paths for the current matrix blueprint.
          wg imageBuilder \
            -b "${{ matrix.blueprint }}" \
            -p "$HOME/cowdogmoo/ansible-collection-workstation" \
            -t "${{ secrets.BOT_TOKEN }}"

      - name: Push image and Create Manifest
        run: |
          # Push the image for each architecture
          for arch in amd64 arm64; do
            echo "Pushing image for architecture: $arch"
            docker push "${{ env.image_name_lowercase }}-${{ matrix.blueprint }}-$arch:${{ env.PRODUCT_VERSION }}"
          done

          # Create and push the manifest for each blueprint
          echo "Creating and Pushing manifest for ${{ matrix.blueprint }}..."
          docker manifest create "${{ env.image_name_lowercase }}-${{ matrix.blueprint }}:${{ env.PRODUCT_VERSION }}" \
            --amend "${{ env.image_name_lowercase }}-${{ matrix.blueprint }}-amd64:${{ env.PRODUCT_VERSION }}" \
            --amend "${{ env.image_name_lowercase }}-${{ matrix.blueprint }}-arm64:${{ env.PRODUCT_VERSION }}"
          docker manifest push "${{ env.image_name_lowercase }}-${{ matrix.blueprint }}:${{ env.PRODUCT_VERSION }}"

      # For debugging:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
