---
name: Container Image Builder
on:
  pull_request:
  push:
    branches: [main, container]

env:
  PRODUCT_VERSION: "latest"
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  container-image-builder:
    name: Build container images using warpgate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@2986852ad836768dfea7781f31828eb3e17990fa # v1.6.2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: cowdogmoo
          password: "${{ steps.app-token.outputs.token }}"

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: "1.21.0"
          cache-dependency-path: "**/*.sum"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Set up warpgate
        run: |
          go mod tidy
          go build -o wg
          sudo mv wg /usr/local/bin/wg

      - name: Clone ansible-collection-workstation
        run: |
          mkdir -p ~/cowdogmoo
          git clone https://github.com/CowDogMoo/ansible-collection-workstation.git ~/cowdogmoo/ansible-collection-workstation

      # - name: Run image builder for each blueprint
      #   run: |
      #     for bp in $(ls blueprints); do
      #         echo "Processing blueprint: $bp"
      #         # Run the wg imageBuilder command with the correct paths.
      #         wg imageBuilder \
      #           -b "$bp" \
      #           -p "$HOME/cowdogmoo/ansible-collection-workstation" \
      #           -t "${{ secrets.BOT_TOKEN }}"
      #     done

      - name: Run image builder for each blueprint
        run: |
          echo "${{ steps.app-token.outputs.token }} | tee /tmp/token"
          # Run the wg imageBuilder command with the correct paths.
          wg imageBuilder \
            -b "runzero-explorer" \
            -p "~/cowdogmoo/ansible-collection-workstation" \
            -t "${{ steps.app-token.outputs.token }}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true

      - name: Test
        run: docker run --rm ${{ env.IMAGE_NAME }}:latest
