---
name: Build and Publish Container Images
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PRODUCT_VERSION: "latest"
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  # # Used for testing locally with act
  # IMAGE_NAME: ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/${{ secrets.GITHUB_REPOSITORY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # # Used for testing locally with act
          # username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Convert IMAGE_NAME to lowercase
        run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and export to Docker (Test Image)
        uses: docker/bake-action@7a5dfed3550ca014665af2a27af8fc9d7284b9b3 # v4
        with:
          set: "*.tags=ghcr.io/cowdogmoo/atomic-red:latest"
          provenance: false # Stop unknown/unknown images from being pushed
          workdir: ./dockerfiles/atomic-red
          push: true
