---
name: Build and Publish Container Images
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PRODUCT_VERSION: "latest"
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  # # Used for testing locally with act
  # IMAGE_NAME: ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/${{ secrets.GITHUB_REPOSITORY_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # # Used for testing locally with act
          # username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Convert IMAGE_NAME to lowercase
        run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and export to Docker (Test Image)
        uses: docker/bake-action@2e3d19baedb14545e5d41222653874f25d5b4dfb # v5
        with:
          set: "*.tags=ghcr.io/cowdogmoo/atomic-red:latest"
          provenance: false # Stop unknown/unknown images from being pushed
          workdir: ./dockerfiles/atomic-red
          push: true
