---
name: Pre-Commit
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  schedule:
    # Run once a week (see https://crontab.guru)
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: pre-commit-${{ github.run_id }}

env:
  DEBIAN_FRONTEND: noninteractive
  GO_VERSION: 1.24.0
  PYTHON_VERSION: 3.12.6
  TASK_X_REMOTE_TASKFILES: 1
  TASK_VERSION: 3.38.0

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write # Allows merge queue updates
  security-events: write # Required for GitHub Security tab

jobs:
  pre-commit:
    name: Update pre-commit hooks and run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Setup git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Install go module dependencies
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  btrfs-progs \
                                  libgpgme-dev \
                                  libbtrfs-dev \
                                  pkg-config

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Setup go-task
        uses: rnorton5432/setup-task@eec4717ae80f02d1614a4fecfa4a55d507768696 # v1.0.0
        if: always()
        with:
          task-version: ${{ env.TASK_VERSION }}

      - name: Run pre-commit
        run: task -y run-pre-commit || true
