---
name: Pre-Commit
on:
  pull_request:
    types:
      - opened
      - synchronize
  # Run once a week (see https://crontab.guru)
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  pre-commit:
    name: Update pre-commit hooks and run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: "1.22.2"

      - name: Install go module dependencies
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          go install github.com/magefile/mage@latest

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  btrfs-progs \
                                  libgpgme-dev \
                                  libbtrfs-dev \
                                  pkg-config

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run go mod tidy - necessary to avoid errors with renovatebot PRs
        run: go mod tidy

      - name: Commit go.mod and go.sum changes to keep pre-commit happy
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add go.mod go.sum
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Update go.mod and go.sum"

      - name: Install pre-commit dependencies
        run: mage installDeps

      - name: Run pre-commit
        run: mage runPreCommit
