---
name: Renovate
on:
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
  schedule:
    # Run every week on sunday and wednesday at 00:00 UTC
    - cron: "0 0 * * 0,3"
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: boolean
        default: false
        required: true
      logLevel:
        description: Log Level
        type: choice
        default: info
        options:
          - debug
          - info
        required: true
      version:
        description: Renovate Version
        default: latest
        required: true

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}

# Retrieve BOT_USER_ID via `curl -s "https://api.github.com/users/${BOT_USERNAME}%5Bbot%5D" | jq .id`
env:
  PYTHON_VERSION: 3.13.3
  RENOVATE_GIT_AUTHOR: "${{ secrets.BOT_USERNAME }} <${{ secrets.BOT_USER_ID }}+${{ secrets.BOT_USERNAME }}[bot]@users.noreply.github.com>"

# Permissions block for GitHub App
permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  statuses: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python dependencies
        run: python3 -m pip install pre-commit

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Install go module dependencies
        run: |
          # Install shfmt
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

          # Install goimports
          go install golang.org/x/tools/cmd/goimports@latest

          # Install gocyclo
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

          # Install gocritic
          go install github.com/go-critic/go-critic/cmd/gocritic@latest

          # Add Go bin directory to PATH
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: latest
          install-only: true

      - name: Renovate
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        env:
          LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
          RENOVATE_DRY_RUN: "${{ inputs.dryRun }}"
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
        with:
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ inputs.version || 'latest' }}"
