---
name: Warpgate Image Builder
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_DEFAULT_REGION: us-west-1
  DEBIAN_FRONTEND: noninteractive
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  PRODUCT_VERSION: latest
  RUNZERO_DOWNLOAD_TOKEN: ${{ secrets.RUNZERO_DOWNLOAD_TOKEN }}
  TZ: UTC

permissions:
  id-token: write
  contents: read

jobs:
  generate-blueprints:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  btrfs-progs \
                                  fuse-overlayfs \
                                  libgpgme-dev \
                                  libbtrfs-dev \
                                  pkg-config \
                                  slirp4netns \
                                  uidmap

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: "**/*.sum"

      - name: Setup warpgate
        run: |
          go mod tidy
          go build -o wg
          sudo mv wg /usr/local/bin/wg

      - name: Generate list of blueprints
        id: set-matrix
        run: |
          matrix_json=$(echo '[
            {"blueprint": "test", "path": "'"${PWD}/blueprints/test"'"}
          ]' | jq -c .)
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  image-builder:
    needs: generate-blueprints
    name: Build container images using warpgate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blueprint: ${{fromJson(needs.generate-blueprints.outputs.matrix)}}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          role-session-name: WarpgateAMIBuilder

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                                  btrfs-progs \
                                  fuse-overlayfs \
                                  libgpgme-dev \
                                  libbtrfs-dev \
                                  pkg-config \
                                  slirp4netns \
                                  uidmap

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: "**/*.sum"

      - name: Restore Go Modules cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-go-

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Setup warpgate
        run: |
          go mod tidy
          go build -o wg
          sudo mv wg /usr/local/bin/wg

      - name: Clone ansible-collection repositories
        run: |
          git clone https://github.com/CowDogMoo/ansible-collection-workstation.git ${{ github.workspace }}/ansible-collection-workstation
          git clone https://github.com/l50/ansible-collection-arsenal.git ${{ github.workspace }}/ansible-collection-arsenal

      - name: Make repository name lowercase
        id: lower-repo
        run: |
          echo "repo_owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Configure containers storage to use vfs driver and ignore chown errors
        run: |
          sudo rm -rf /var/lib/containers/storage
          sudo rm -rf $HOME/.local/share/containers/storage

          mkdir -p $HOME/.config/containers
          mkdir -p $HOME/.local/share/containers/storage/vfs/dir

          cat <<EOF > $HOME/.config/containers/storage.conf
          [storage]
            driver = "overlay"
          [storage.options]
            mount_program = "/usr/bin/fuse-overlayfs"
          [storage.options.overlay]
            ignore_chown_errors = "true"
          EOF

          sudo chown -R runner:docker $HOME/.local/share/containers/storage
          sudo chmod -R 755 $HOME/.local/share/containers/storage

      - name: Docker login
        run: |
          echo "${{ secrets.BOT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Run image builder for each blueprint
        run: |
          blueprint_name="${{ matrix.blueprint.blueprint }}"
          export RUNZERO_DOWNLOAD_TOKEN="${{ secrets.RUNZERO_DOWNLOAD_TOKEN }}"
          provision_path=""

          echo "Blueprint name: ${{ matrix.blueprint.blueprint }}"
          if [[ "${{ matrix.blueprint.blueprint }}" == "test" ]]; then
            provision_path="${{ matrix.blueprint.path }}/scripts/provision.sh"
          else
            echo "Unknown blueprint: ${{ matrix.blueprint.blueprint }}"
            exit 1
          fi

          timeout 2h wg imageBuilder \
            -b "$blueprint_name" \
            -p "$provision_path" \
            -t "${{ secrets.BOT_TOKEN }}"
        working-directory: ${{ github.workspace }}

      - name: Verify pushed images
        run: |
          echo "${{ secrets.BOT_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/l50/test:latest
